import { Inter } from "next/font/google";
import "./globals.css";
import LoginScreen from "./LoginScreen";
import {authOptions} from "./api/auth/[...nextauth]/route";
import {getServerSession} from "next-auth";
import Header from "./Header.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  console.log({session});
  return (
    <html lang="en">
      <body className={inter.className}>
        {!session && (
        <LoginScreen />
        )}
        {session && (
          <>
          <Header />
           {children}

          </>
        )}
        </body>
    </html>
  );
}
